version: '3.8'

services:
  microservice1:
    build:
      context: ./cadastro
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - rabbitmq

  microservice2:
    build:
      context: ./notificacao
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"   
      - "15672:15672" 
